# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47ed53a4950c64ff0cc5ef56f3fcd2f163cb261f61c5a99e26bacc7faa458e2f843daa94de0b67bd1df277eb0f55f0bb37ecc03457a99741bac7cf5cca89a7c1

test:
  secret_key_base: 0846d8d11e14914afc94f50d6686d78b86948281bacc61c85aa67997e9b18fe9c3f41b48f817ea2c4a45f31fd3b155e79708c4d93852d9cc6ceca18f535556ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
